config:
  prefix: '~'
  button-style: SECONDARY
  thread-name: buttons-pressed
  num-per-row: 5 # max 4 rows with max 5 items per row b/c menu = 1 row
                 #  (no more than 20 sounds per category)
categories:
  animals:
    cat:
      emoji: ğŸ±
    dog:
      emoji: ğŸ¶
    cow:
      emoji: ğŸ®
    fox:
      emoji: ğŸ¦Š
    horse:
      emoji: ğŸ´
    dolphin:
      emoji: ğŸ¬
    whale:
      emoji: ğŸ‹
    pig:
      emoji: ğŸ·
    bear:
      emoji: ğŸ»
    wolf:
      emoji: ğŸº
    hen:
      emoji: ğŸ”
    monkey:
      emoji: ğŸµ
    chick:
      emoji: ğŸ¤
    lion:
      emoji: ğŸ¦
    owl:
      emoji: ğŸ¦‰
    snake:
      emoji: ğŸ
    mouse:
      emoji: ğŸ­
    frog:
      emoji: ğŸ¸
    dragon:
      emoji: ğŸ²
    beaver:
      emoji: ğŸ¦«
    
  anime:
    one-piece:
      emoji: one-piece
    naruto:
      emoji: naruto
    psycho-pass:
      emoji: psycho-pass
    ohshc:
      emoji: ğŸ’‹

  dnd:
    dice-roll:
      emoji: ğŸ²
    critical-success:
      emoji: ğŸ‰
    critical-fail:
      emoji: â˜ ï¸
    suspicious:
      emoji: ğŸ‘€
    mage:
      emoji: ğŸ§™
    fairy:
      emoji: ğŸ§š

  monsters:
    roar:
      emoji: roar
    growl:
      emoji: growl

  transportation:
    train:
      emoji: ğŸšŠ
    car:
      emoji: ğŸš—
    police-car:
      emoji: ğŸš“
    ambulance:
      emoji: ğŸš‘
    airplane:
      emoji: âœˆï¸
    helicopter:
      emoji: ğŸš
    ship:
      emoji: ğŸš¢
    anchor:
      emoji: âš“
    horse-gallop:
      emoji: ğŸ‡

  weapons:
    arrow-hit:
      emoji: ğŸ¹ âœ…
    arrow-miss:
      emoji: ğŸ¹ âŒ
    axe-hit:
      emoji: ğŸª“ âœ…
